# Generated by Django 2.0.5 on 2018-05-04 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='parent_page',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='page',
            name='denormalised_path',
            field=models.TextField(default='', editable=False, help_text="Ordered slash-separated list of parent `Page`s' slugs, starting from the top level `Page`.  This does not include the current `Page`."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.RemoveField(
            model_name='page',
            name='site',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('denormalised_path', 'slug')},
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
