# Generated by Django 2.0.5 on 2018-05-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180504_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='denormalised_path',
            field=models.TextField(db_index=True, editable=False, help_text="Ordered slash-separated list of parent `Page`s' slugs, starting from the top level `Page`.  This does not include the current `Page`."),
        ),
    ]
