# Generated by Django 2.0.5 on 2018-05-15 21:12

from django.db import migrations, models


def denormalise_titles(page, accumulator=''):
    page.denormalised_titles = accumulator
    page.save()

    if accumulator == '':
        accumulator = page.title
    else:
        accumulator = '\n'.join([accumulator, page.title])

    for child in page.children.all():
        denormalise_titles(child, accumulator)


def redenormalise_titles(apps, schema_editor):
    Page = apps.get_model('cms', 'Page')

    for page in Page.objects.filter(parent=None):
        denormalise_titles(page)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180515_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='denormalised_titles',
            field=models.TextField(default='', editable=False, help_text="Ordered newline-separated list of parent `Page`s' titles, starting from the top level `Page`.  This does not include the current `Page`."),
            preserve_default=False,
        ),
        migrations.RunPython(redenormalise_titles, migrations.RunPython.noop),
    ]
