# Generated by Django 2.0.5 on 2018-05-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20180519_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
