# Generated by Django 2.0.5 on 2018-05-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_block_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
